<?php $this->declareVars('breadcrumbContent', 'breadcrumbCount') ?>
<?php $this->breadcrumbCount = count($this->breadcrumb) ?>

<?php $this->placeholder('breadcrumbContent')->captureStart() ?>
   <?php foreach($this->breadcrumb as $index => $page) : ?>
        <?php if ($index + 1 >= $this->breadcrumbCount): ?>
            <?php $this->currentPageTitle = $page['title'] ?>
            <?php continue ?>
        <?php endif ?>

        &nbsp;&nbsp;/
        <?php if (!$page['url']) : ?>
            <span><?php echo $page['title'] ?></span>
        <?php else: ?>
            <a href="<?php echo $this->url('page', ['page_name' => $page['url']], ['force_canonical' => true]) ?>">
                <?php echo $page['title'] ?>
            </a>
        <?php endif ?>
    <?php endforeach ?>
<?php $this->placeholder('breadcrumbContent')->captureEnd() ?>

<section class="small-section bg-gray-lighter">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-6">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0"><?php echo $this->currentPageTitle ?></h1>
                <?php if (!empty($this->layout()->page['description'])): ?>
                    <div class="hs-line-4 font-alt black">
                        <?php echo $this->escapeHtml($this->layout()->page['description']) ?>
                    </div>
                <?php endif ?>
            </div>
            <div class="col-md-6 mt-30">
                <div class="mod-breadcrumbs font-alt align-right">
                    <a href="<?php echo $this->url('page', [], ['force_canonical' => true]) ?>"><?php echo $this->translate('Home') ?></a>
                    <?php echo $this->placeholder('breadcrumbContent') ?>
                </div>                
            </div>
        </div>
    </div>
</section>