<?php $this->declareVars('localizationPages', 'userPage') ?>
<?php $this->localizationPages = new ArrayObject ?>
<?php $this->userPage = $this->pageUrl('user', [], null, true) ?>

<nav class="main-nav js-stick">
    <div class="full-wrapper relative clearfix">
        <!-- Logo ( * your text or image into link tag *) -->
        <div class="nav-logo-wrap local-scroll">
            <?php echo $this->pageInjectWidget('logo') ?>
            <a href="<?php echo $this->url('page') ?>" class="logo">
                <img src="<?php echo $this->layoutAsset('logo-dark.png', 'image') ?>"  width="118" height="27" alt="<?php echo $this->escapeHtmlAttr($this->translate('Home')) ?>" />
            </a>
        </div>
        <div class="mobile-nav">
            <i class="fa fa-bars"></i>
        </div>
        <div class="inner-nav desktop-nav">
            <ul class="clearlist">
                <?php echo $this->menu_items ?>
                <li><a>&nbsp;</a></li>

                <?php if(!$this->userIsGuest()): ?>
                  <!-- user menu -->
                  <li>
                        <?php if (false !== $this->userPage): ?>
                           <a class="mn-has-sub" href="<?php echo $this->url('page', ['page_name' => $this->userPage, 'slug' => $this->userIdentity()['slug']], ['force_canonical' => true]) ?>">
                                <?php echo $this->translate('Hello') ?>, <?php echo $this->escapeHtml($this->userIdentity()['nick_name']) ?>
                                <i class="fa fa-angle-down"></i>
                            </a>
                       <?php else: ?>
                            <a class="mn-has-sub" href="#">
                                <?php echo $this->translate('Hello') ?>, <?php echo $this->escapeHtml($this->userIdentity()['nick_name']) ?>
                                <i class="fa fa-angle-down"></i>
                            </a>
                       <?php endif ?>
 
                       <ul class="mn-sub">
                            <?php if ($this->pageUserMenu()): ?>
                                <?php foreach($this->pageUserMenu() as $menu) : ?>
                                    <li>
                                        <a href="<?php echo $this->url('page', ['page_name' => $menu['url']], ['force_canonical' => true]) ?>"><?php echo $menu['title'] ?></a>
                                    </li>
                                 <?php endforeach ?>
                            <?php endif ?>     
                            <li>
                                <a href="javascript:void(0)" onclick="ajaxQuery('logged-user-menu', '<?php echo $this->url('application/page', ['controller' => 'user-ajax', 'action' => 'ajax-logout']) ?>', function(){location.href='<?php echo $this->url('page', [], ['force_canonical' => true]) ?>'}, 'post', {}, false)">
                                    <?php echo $this->translate('Logout') ?>
                                </a>
                            </li>
                       </ul>
                  </li>
                  <!-- end user menu -->
                <?php endif ?>

                <?php if (count($this->localization()->getAllLocalizations()) > 1): ?>
                      <?php foreach($this->localization()->getAllLocalizations() as $language): ?>
                          <?php if (empty($this->layout()->page['dynamic_page']) && false !== $this->pageUrl($this->layout()->page['slug'], [], $language['language'])): ?>
                              <?php 
                                  $this->localizationPages[$language['language']]['url'] = $this->pageUrl($this->layout()->page['slug'], [], $language['language']); 
                                  $this->localizationPages[$language['language']]['exists'] = true; 
                              ?>
                          <?php elseif (false !== $this->pageUrl(null, [], $language['language'])): ?>
                              <?php 
                                  $this->localizationPages[$language['language']]['url'] = $this->pageUrl(null, [], $language['language']);
                                  $this->localizationPages[$language['language']]['exists'] = false;
                              ?>
                          <?php endif ?>
                      <?php endforeach ?>
                  <?php endif ?>

                  <?php if (count($this->localizationPages) > 1): ?>
                      <li>
                          <!-- language switcher -->
                           <a class="mn-has-sub" href="#">
                               <img src="<?php  echo $this->layoutAsset('icon/flag/' . $this->escapeHtml($this->localization()->getCurrentLocalization()['language']) . '.gif', 'image') ?>" alt="<?php echo $this->escapeHtmlAttr($this->localization()->getCurrentLocalization()['description']) ?>" />
                               <?php echo $this->escapeHtml($this->localization()->getCurrentLocalization()['language']) ?><i class="fa fa-angle-down"></i>
                           </a>
                          <ul class="mn-sub"> 
                              <?php foreach ($this->localizationPages as $language => $page): ?>
                                  <li>
                                      <a <?php if ($language == $this->localization()->getCurrentLanguage()): ?>class="active"<?php endif ?> href="<?php echo $this->url('page', ['language' => $language, 'page_name' => $page['url']], ['force_canonical' => true, 'query' => ($page['exists'] ? $this->applicationRoute()->getQuery() : [])], true) ?>">
                                          <img src="<?php  echo $this->layoutAsset('icon/flag/' . $this->escapeHtml($language) . '.gif', 'image') ?>" alt="<?php echo $this->escapeHtmlAttr($this->localization()->getAllLocalizations()[$language]['description']) ?>" />
                                          <?php echo $this->escapeHtml($this->localization()->getAllLocalizations()[$language]['description']) ?>
                                      </a>
                                  </li>
                              <?php endforeach ?>
                          </ul>
                          <!-- end laguage swither -->
                      </li>
                <?php endif ?>
 
            </ul>
        </div>
    </div>
</nav>
