<?php if (count($this->items) > 1): ?>
    <?php $this->declareVars('uncategorized', 'content', 'index', 'randPrefix') ?>
    <?php $this->uncategorized = null ?>
    <div class="panel-group" id="<?php echo $this->escapeHtmlAttr($this->name) ?>">
        <?php foreach ($this->items as $category => $content) : ?>
            <?php if (null == $category): ?>
                <?php $this->uncategorized .= $content; continue; ?>
            <?php endif; ?>
            <?php $this->index++ ?>
            <?php $this->randPrefix = $this->escapeHtmlAttr($this->applicationRandId()) ?>
            <dl class="accordion">
                <dt>
                    <a href="" class="<?php if (($this->index == 1 && ! (array) $this->openCategories) || (in_array($category, (array) $this->openCategories))): ?>active<?php endif ?>"><?php echo $this->translate($category) ?></a>
                </dt>
                <dd>
                    <?php echo $content ?>
                </dd>
            </dl>
        <?php endforeach; ?>
        <?php echo $this->uncategorized ?>
    </div>
<?php else: ?>
    <?php echo current($this->items) ?>
<?php endif ?>