            </div>
            <div id="footer-container" class="container-fluid">
                <footer class="bg-gray-lighter footer">
                    <div class="container">
                    <?php echo $this->pageInjectWidget('footer') ?>
                    <?php echo $this->pageFooterMenu(5, /* max rows */ 4 /* max columns per row */) ?>
                    </div>
                    
                    <div class="container">                
                        <!-- Footer Logo -->
                        <div class="mb-30 ">
                            <a href="#top"><img width="78" height="36" src="<?php echo $this->layoutAsset('logo-footer.png', 'image') ?>" /></a>
                        </div>
                        <!-- End Footer Logo -->
                        
                        <!-- Social Links -->
                        <div class="footer-social-links mb-110 mb-xs-60">
                            <a target="_blank" title="Facebook" href="#"><i class="fa fa-facebook"></i></a>
                            <a target="_blank" title="Twitter" href="#"><i class="fa fa-twitter"></i></a>
                            <a target="_blank" title="Behance" href="#"><i class="fa fa-behance"></i></a>
                            <a target="_blank" title="LinkedIn+" href="#"><i class="fa fa-linkedin"></i></a>
                            <a target="_blank" title="Pinterest" href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                        <!-- End Social Links -->
    
                        <!-- Footer Text -->
                        <div class="footer-text">
                            <!-- Copyright -->
                            <div class="footer-copy font-alt">
                                &copy; <?php echo $this->applicationSetting('application_site_name') ?> <?php echo date('Y') ?>
                            </div>
                            <!-- End Copyright -->
    
                            <?php if ((int) $this->applicationSetting('layout_select')):  ?>
                                <?php $this->declareVars('layoutsList') ?>
                                <?php $this->layoutsList = $this->layoutList()->getLayouts() ?>
                                <?php if (count($this->layoutsList) > 1): ?>
                                    <?php echo $this->layoutList()->getLayoutsSelectBox('select-layout-link') ?>
                                        <?php echo $this->translate('Layout') ?> - <a href="#" id="select-layout-link"><?php echo $this->escapeHtml($this->layoutList()->getActiveLayout()) ?></a>
                                    </p>
                                <?php endif ?>
                            <?php endif ?>                       
                        </div>
                        <!-- End Footer Text --> 
                     </div>
                </footer>
            </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>