<?php $this->declareVars('localizationPages') ?>
<?php $this->localizationPages = new ArrayObject ?>
<?php echo $this->doctype() ?>
<html dir="<?php echo $this->localization()->getCurrentLanguageDirection() ?>" lang="<?php echo $this->localization()->getCurrentLanguage() ?>">
    <head>
        <?php echo $this->pageInjectWidget('head') ?>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->applicationSetting('application_site_name'))->setSeparator(' - ')->setAutoEscape(false)->setTranslatorEnabled(false) ?>
        <base href="<?php echo $this->basePath() . '/' ?>" />

        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1')
            ->appendName('generator', $this->applicationSetting('application_generator'))
        ?>

        <!-- styles -->
        <?php $this->layoutHeadLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->layoutAsset('icon/favicon.ico', 'image')])
            ->prependStylesheet($this->layoutAsset('frontend.css', 'css')) 
            ->prependStylesheet($this->layoutAsset('jquery-ui.css', 'css'))
            ->prependStylesheet($this->layoutAsset('rhytm-style.css', 'css'))
            ->prependStylesheet($this->layoutAsset('rhytm-style-responsive.css', 'css'))
            ->prependStylesheet($this->layoutAsset('vertical-rhythm.min.css', 'css'))
            ->prependStylesheet($this->layoutAsset('bootstrap-theme.css', 'css'))
            ->prependStylesheet($this->layoutAsset('bootstrap.css', 'css'))
        ?>

        <?php if (!$this->localization()->isCurrentLanguageLtr()): ?>
            <?php $this->layoutHeadLink()
                ->appendStylesheet($this->layoutAsset('bootstrap.rtl.css', 'css'))
                ->appendStylesheet($this->layoutAsset('frontend.rtl.css', 'css'))?>
        <?php endif; ?>

        <?php echo $this->layoutHeadLink() ?>

        <!-- scripts -->
        <?php echo $this->layoutHeadScript()
            ->prependFile($this->layoutAsset('all.js'))
            ->prependFile($this->layoutAsset('jquery.fitvids.js'))
            ->prependFile($this->layoutAsset('jquery.sticky.js'))
            ->prependFile($this->layoutAsset('jquery.waitforimages.js'))
            ->prependFile($this->layoutAsset('functions.js'))
            ->prependFile($this->layoutAsset('require.js'))
            ->prependFile($this->layoutAsset('jquery.cookie.js'))
            ->prependFile($this->layoutAsset('bootstrap.js'))
            ->prependFile($this->layoutAsset('jquery-ui.js'))            
            ->prependFile($this->layoutAsset('jquery.js'))
            ->prependFile($this->layoutAsset('respond.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
            ->prependFile($this->layoutAsset('html5shiv.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
        ?>
    </head>
    <body>
        <?php echo $this->pageInjectWidget('body') ?>
        
        <!-- Navigation panel -->
            <nav class="main-nav js-stick">
                <div class="full-wrapper relative clearfix">
                    <!-- Logo ( * your text or image into link tag *) -->
                    <div class="nav-logo-wrap local-scroll">
                        <a href="<?php echo $this->url('page') ?>" class="logo">
                            <img src="<?php echo $this->layoutAsset('logo-dark.png', 'image') ?>" width="118" height="27" alt="" />
                        </a>
                    </div>
                    <div class="mobile-nav">
                        <i class="fa fa-bars"></i>
                    </div>
                    
                    <!-- Main Menu -->
                    <div class="inner-nav desktop-nav">
                        <ul class="clearlist">
                                                        
                            <!-- Item With Sub -->
                            <li>
                                <a href="#" class="mn-has-sub">Portfolio <i class="fa fa-angle-down"></i></a>
                                
                                <!-- Sub -->
                                <ul class="mn-sub">
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Boxed <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="portfolio-boxed-2col.html">2 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-3col.html">3 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-4col.html">4 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-5col.html">5 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-blackhover.html">Black Hovers</a>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Boxed (Gutter) <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="portfolio-boxed-gutter-2col.html">2 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-gutter-3col.html">3 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-gutter-4col.html">4 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-gutter-5col.html">5 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-gutter-blackhover.html">Black Hovers</a>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Boxed (Titles) <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="portfolio-boxed-titles-2col.html">2 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-titles-3col.html">3 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-titles-4col.html">4 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-titles-5col.html">5 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-boxed-titles-blackhover.html">Black Hovers</a>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Wide <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="portfolio-wide-2col.html">2 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-3col.html">3 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-4col.html">4 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-5col.html">5 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-blackhover.html">Black Hovers</a>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Wide (Gutter) <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="portfolio-wide-gutter-2col.html">2 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-gutter-3col.html">3 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-gutter-4col.html">4 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-gutter-5col.html">5 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-gutter-blackhover.html">Black Hovers</a>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Wide (Titles) <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="portfolio-wide-titles-2col.html">2 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-titles-3col.html">3 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-titles-4col.html">4 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-titles-5col.html">5 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-wide-titles-blackhover.html">Black Hovers</a>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Masonry <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="portfolio-masonry-2col.html">2 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-masonry-3col.html">3 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-masonry-4col.html">4 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-masonry-5col.html">5 Columns</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-masonry-blackhover.html">Black Hovers</a>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Single <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="portfolio-single-1.html">Single 1</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-single-2.html">Single 2</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-single-3.html">Single 3</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-single-4.html">Single 4</a>
                                            </li>
                                            <li>
                                                <a href="portfolio-single-5.html">Single 5</a>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                    <li>
                                        <a href="portfolio-parallax.html">Parallax</a>
                                    </li>
                                    
                                    <li>
                                        <a href="portfolio-promo.html">Promo</a>
                                    </li>
                                    
                                </ul>
                                <!-- End Sub -->
                                
                            </li>
                            <!-- End Item With Sub -->
                            
                            <!-- Item With Sub -->
                            <li>
                                <a href="#" class="mn-has-sub active">Blog <i class="fa fa-angle-down"></i></a>
                                
                                <!-- Sub -->
                                <ul class="mn-sub">
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Classic <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="blog-classic-sidebar-left.html">Sidebar Left</a>
                                            </li>
                                            <li>
                                                <a href="blog-classic-sidebar-right.html">Sidebar Right</a>
                                            </li>
                                            <li>
                                                <a href="blog-classic-fullwidth.html">Fullwidth</a>
                                            </li>
                                        </ul>
                                        
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Columns <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="blog-columns-2col.html">2 Columns</a>
                                            </li>
                                            <li>
                                                <a href="blog-columns-3col.html">3 Columns</a>
                                            </li>
                                            <li>
                                                <a href="blog-columns-4col.html">4 Columns</a>
                                            </li>
                                        </ul>
                                        
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Masonry <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="blog-masonry-2col.html">2 Columns</a>
                                            </li>
                                            <li>
                                                <a href="blog-masonry-3col.html">3 Columns</a>
                                            </li>
                                            <li>
                                                <a href="blog-masonry-4col.html">4 Columns</a>
                                            </li>
                                        </ul>
                                        
                                    </li>
                                    
                                    <li>
                                        <a href="#" class="mn-has-sub">Single <i class="fa fa-angle-right right"></i></a>
                                    
                                        <ul class="mn-sub">
                                            <li>
                                                <a href="blog-single-sidebar-left.html">Sidebar Left</a>
                                            </li>
                                            <li>
                                                <a href="blog-single-sidebar-right.html">Sidebar Right</a>
                                            </li>
                                            <li>
                                                <a href="blog-single-fullwidth.html">Fullwidth</a>
                                            </li>
                                        </ul>
                                        
                                    </li>
                                    
                                    
                                </ul>
                                <!-- End Sub -->
                                
                            </li>
                            <!-- End Item With Sub -->
                            
                            <!-- Item With Sub -->
                            <li>
                                <a href="#" class="mn-has-sub">Shop <i class="fa fa-angle-down"></i></a>
                                
                                <!-- Sub -->
                                <ul class="mn-sub to-left">
                                    
                                    <li>
                                        <a href="shop-columns-2col.html">2 Columns</a>
                                    </li>
                                    <li>
                                        <a href="shop-columns-3col.html">3 Columns</a>
                                    </li>
                                    <li>
                                        <a href="shop-columns-4col.html">4 Columns</a>
                                    </li>
                                    <li>
                                        <a href="shop-single.html">Single Product</a>
                                    </li>
                                    <li>
                                        <a href="shop-cart.html">Shopping Cart</a>
                                    </li>
                                    
                                </ul>
                                <!-- End Sub -->
                                
                            </li>
                            <!-- End Item With Sub -->
                            
                            <!-- Divider -->
                            <li><a>&nbsp;</a></li>
                            <!-- End Divider -->
                            
                            <!-- Search -->
                            <li>
                                <a href="#" class="mn-has-sub"><i class="fa fa-search"></i> Search</a>
                                
                                <ul class="mn-sub">
                                    
                                    <li>
                                        <div class="mn-wrap">
                                            <form method="post" class="form">
                                                <div class="search-wrap">
                                                    <button class="search-button animate" type="submit" title="Start Search">
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                    <input type="text" class="form-control search-field" placeholder="Search...">
                                                </div>
                                            </form>
                                        </div>
                                    </li>
                                    
                                </ul>
                                
                            </li>
                            <!-- End Search -->
                            
                            <!-- Cart -->
                            <li>
                                <a href="#"><i class="fa fa-shopping-cart"></i> Cart(0)</a>
                            </li>
                            <!-- End Cart -->
                            
                            <!-- Languages -->
                            <li>
                                <a href="#" class="mn-has-sub">Eng <i class="fa fa-angle-down"></i></a>
                                
                                <ul class="mn-sub">
                                    
                                    <li><a href="">English</a></li>
                                    <li><a href="">France</a></li>
                                    <li><a href="">Germany</a></li>
                                    
                                </ul>
                                
                            </li>
                            <!-- End Languages -->
                            
                        </ul>
                    </div>
                    <!-- End Main Menu -->
                    

                </div>
            </nav>
            <!-- End Navigation panel -->
            