<?php $this->declareVars('newsListUrl') ?>
<?php $this->newsListUrl = $this->pageUrl('news-list') ?>

<div id="preview-news">
    <?php if ($news['image']): ?>
        <img id="preview-image" alt="<?php echo $this->escapeHtmlAttr($news['title']) ?>" src="<?php echo $this->escapeHtmlAttr($this->newsImageUrl($news['image'], false)) ?>" />
    <?php endif ?>
    <p>
        <strong>
            <time datetime="<?php echo $this->escapeHtmlAttr(date('Y-m-d H:i', $news['created'])) ?>">
                <?php echo $this->escapeHtml($this->applicationDate($news['created'], ['format' => $this->applicationSetting('news_date_format')])) ?>
            </time>
        </strong>
        <?php echo $this->escapeHtml($news['intro']) ?>
    </p>
    <?php echo $news['text'] ?>
    <?php if(!empty($this->categories)): ?>
        <p>
            <strong><?php echo $this->translate('Categories') ?>:</strong>
            <?php foreach ($this->categories as $category): ?>
                <?php if (false == $this->newsListUrl): ?>
                    <?php echo $this->escapeHtml($category['name']) ?>
                <?php else: ?>
                    <a href="<?php echo $this->url('page', ['page_name' => $this->newsListUrl, 'category' => $category['slug']], ['force_canonical' => true]) ?>"><?php echo $this->escapeHtml($category['name']) ?></a>
                <?php endif ?>
            <?php endforeach ?>
        </p>
    <?php endif ?>
</div>